version: '3'
services:
        mysql_database:
                image: mysql:5.7
                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD: root
                        MYSQL_DATABASE: WordpressDatabase
                        MYSQL_USER: Nitya
                        MYSQL_PASSWORD: admin
                volumes:
                        - mysql:/var/lib/mysql




        wordpress:
               depends_on:
                       - mysql_database
               image: wordpress:latest
               restart: always
               ports: 
                        - "8000:80"
               environment:
                        WORDPRESS_DB_HOST: mysql_db:3306
                        WORDPRESS_DB_USER: Nitya
                        WORDPRESS_DB_PASSWORD: admin
                        WORDPRESS_DB_NAME: WordpressDatabase
               volumes: 
                        ["./:/var/www/html"] 
volumes:
        mysql: {}

